---
title: "COVE"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(tidyverse)
library(gtsummary)
library(janitor)
library(flextable)
canalend <- read_excel("/cloud/project/Boletin_ Epi_Pereira/Datos/canalend.xlsx")
dengue2018 <- read_excel("/cloud/project/Boletin_ Epi_Pereira/Datos/dengue2018.xlsx")
resi_anterior <- readRDS("/cloud/project/Boletin_ Epi_Pereira/Datos/residencia.rds") %>% 
  mutate(semana = as.numeric(semana))
proce_anterior <- readRDS("/cloud/project/Boletin_ Epi_Pereira/Datos/procedencia.rds") %>% 
  mutate(semana = as.numeric(semana))
casos2022 <- readRDS("/cloud/project/Boletin_ Epi_Pereira/Datos/casos2022.rds") %>% 
  mutate(semana = as.numeric(semana))

ira<-read_excel("/cloud/project/Boletin_ Epi_Pereira/Datos/ira.xlsx")
ira2018<-read.csv("/cloud/project/Boletin_ Epi_Pereira/Datos/ira2018.xls")
eda<-read_excel("/cloud/project/Boletin_ Epi_Pereira/Datos/eda.xlsx")
eda2018<-read.csv("/cloud/project/Boletin_ Epi_Pereira/Datos/eda2018.xls")
histoira<-read_excel("/cloud/project/Boletin_ Epi_Pereira/Datos/histo_ira.xlsx")
```

```{r}
actual <- table(casos2022$cod_eve,casos2022$semana)
anterior_resi <- table(resi_anterior$cod_eve, resi_anterior$semana)
anterior_proce <- table(proce_anterior$cod_eve, proce_anterior$semana)
```

---

# General 
Column 
-----------------------------------------------------------------

### **Comportamientos eventos notificados Pereira**

```{r}
casos2022 %>% tabyl(nom_eve) %>% adorn_pct_formatting() %>% arrange(desc(n)) %>% filter() %>%  flextable::flextable()
```



# EISP 1

Column 
-----------------------------------------------------------------

### **Evento 1**

```{r}
plot(actual["300",], type = "l", lwd=3 ,col="red", xlim = c(1,53), ylim = c(0,70), xlab = "Semana", ylab = "Casos", main = "Agresiones probablemente rabicas", cex=0.7)
lines(anterior_proce["300",], type = "l", lwd=5)
legend(5,65, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 70, "Variación relativa", cex = 1.2)
text(15,64, round((sum(actual["300",1:ncol(actual)])-sum(anterior_proce["300",1:ncol(actual)]))/ sum(anterior_proce["300",1:ncol(actual)])*100, digits=1), col = "red")
```

### **Evento 2**

```{r, fig.width=7}
plot(actual["356",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,70), xlab = "Semana", ylab = "Casos", main = "Intento suicida")
lines(anterior_resi["356",], type = "l", lwd=6)
legend(5,65, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 70, "Variación relativa")
text(15,64, round((sum(actual["356",1:ncol(actual)])-sum(anterior_resi["356",1:ncol(actual)]))/ sum(anterior_resi["356",1:ncol(actual)])*100, digits=1), col = "red")
```

Column
---------------------------------------------------------------
### **Evento 3**

```{r}
plot(actual["850",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,50), xlab = "Semana", ylab = "Casos", main="VIH/SIDA")
lines(anterior_resi["850",], type = "l", lwd=6)
legend(5,35, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 45, "Variación relativa", cex = 1.2)
text(15,40, round((sum(actual["850",1:ncol(actual)])-sum(anterior_resi["850",1:ncol(actual)]))/ sum(anterior_resi["850",1:ncol(actual)])*100, digits=1), col = "red", cex = 1.2)
```

### **Evento 4**

```{r}
plot(actual["813",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,50), xlab = "Semana", ylab = "Casos", main = "Tuberculosis")
lines(anterior_resi["813",], type = "l", lwd=6)
legend(5,35, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 45, "Variación relativa")
text(15,40, round((sum(actual["813",1:ncol(actual)])-sum(anterior_resi["813",1:ncol(actual)]))/ sum(anterior_resi["813",1:ncol(actual)])*100, digits=1), col = "red")
```

# EISP 2

Column 
-----------------------------------------------------------------
### **Evento 5**

```{r, fig.width=7}
plot(actual["155",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,70), xlab = "Semana", ylab = "Casos", main = "Cancer de mama y cuello uterino")
lines(anterior_resi["155",], type = "l", lwd=5)
legend(5,65, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 70, "Variación relativa")
text(15,64, round((sum(actual["155",1:ncol(actual)])-sum(anterior_resi["155",1:ncol(actual)]))/sum(anterior_resi["155",1:ncol(actual)])*100, digits=1), col = "red")

```

### **Evento 6**

```{r}
plot(actual["831",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,70), xlab = "Semana", ylab = "Casos", main = "Varicela")
lines(anterior_resi["831",], type = "l", lwd=6)
legend(5,65, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 70, "Variación relativa")
text(15,64, round((sum(actual["831",1:ncol(actual)])-sum(anterior_resi["831",1:ncol(actual)]))/ sum(anterior_resi["831",1:ncol(actual)])*100, digits=1), col = "red")
```

Column
---------------------------------------------------------------
### **Evento 7**

```{r}
plot(actual["110",], type = "l", lwd=3 ,col="red", xlim = c(1,52), ylim = c(0,50), xlab = "Semana", ylab = "Casos", main = "Bajo peso al nacer a termino")
lines(anterior_resi["110",], type = "l", lwd=6)
legend(5,35, c("2021","2022"),col=c("black","red"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
text(15, 45, "Variación relativa")
text(15,40, round((sum(actual["110",1:ncol(actual)])-sum(anterior_resi["110",1:ncol(actual)]))/ sum(anterior_resi["110",1:ncol(actual)])*100, digits=1), col = "red")
```

# Eventos Trazadores 1

Column 
-----------------------------------------------------------------
### **Canal endémico general IRA**

```{r, fig.width=8}
plot(ira$semana, ira$exito, type='l', ylim=c(1,2700), xlim=c(1,52), col="green",lwd=3, xlab="Semana epidemiológica", ylab="Casos", cex=0.6, main = "Canal endémico IRA - Pereira 2021")
lines(ira$alerta, col="red",lwd=3, cex=0.7)
lines(ira2018$casos, col="black", lwd=3, cex=0.7, type = "p")
abline(1300,0,1300, col="yellow", lwd=3)
legend(25,2750, c("IC Inf 95%","IC Sup 95%", "Umbral estacional", "casos 2022"), col=c("green","red","yellow","black"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)

```

### **Canal endémico Hospitalizaciones sala general por IRA**

```{r, fig.width=8}
plot(ira$semana, ira$icinfhosp, type='l', ylim=c(1,100), xlim=c(1,52), col="green",lwd=3, xlab="Semana epidemiológica", ylab="Casos", cex=0.6, main = "")
lines(ira$icsuphosp, col="red",lwd=3, cex=0.7)
abline(44,0,44, col="yellow", lwd=3)
lines(ira2018$c_hosp, col="black", lwd=3, cex=0.7, type = "p")
legend(25,2750, c("IC Inf 95%","IC Sup 95%", "Umbral estacional", "casos 2022"), col=c("green","red","yellow","black"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
```

Column
---------------------------------------------------------------
### **Canal endémico Hoospitalizaciones por IRA en UCI**

```{r, fig.width=8}
plot(ira$semana, ira$icinfuci, type='l', ylim=c(1,35), xlim=c(1,52), col="green",lwd=3, xlab="Semana epidemiológica", ylab="Casos", cex=0.6, main = "")
lines(ira$icsupuci, col="red",lwd=3, cex=0.7)
abline(4,0,4, col="yellow", lwd=3)
lines(ira2018$c_uci, col="black", lwd=3, cex=0.7, type = "p")
legend(35,20, c("IC Inf 95%","IC Sup 95%", "Umbral estacional", "2022"), col=c("green","red","yellow","black"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
```

### **Canal endémico IRA en Consulta externa - Urgencias**

```{r, fig.width=8}
plot(ira$semana, ira$icinfext, type='l', ylim=c(1,2700), xlim=c(1,52), col="green",lwd=3, xlab="Semana epidemiológica", ylab="Casos", cex=0.6, main = "")
lines(ira$icsupext, col="red",lwd=3, cex=0.7)
abline(1504,0,1504, col="yellow", lwd=3)
lines(ira2018$c_ext, col="black", lwd=3, cex=0.7, type = "p")
legend(25,2800, c("IC Inf 95%","IC Sup 95%", "Umbral estacional", "2022"), col=c("green","red","yellow","black"), lty = c(1,1), lwd = c(2,2), bty="n", cex=1)
```

# Eventos Trazadores 2

Column
-----------------------------------------------------------------

### **Canal endémico EDA**

```{r, fig.width=8}
plot(eda$semana, eda$exito, type='l', ylim=c(0,1500), xlim=c(1,52), col="green",lwd=2, xlab="Semana epidemiológica", ylab="Casos", main = "")
lines(eda$alerta, col="red",lwd=2)
abline(683,0,683, col="yellow", lwd=3)
lines(eda2018$semana,eda2018$casos, col="black",lwd=2, cex=0.7)
legend(25,1400, c("IC inf 95%","Media", "IC sup 95%", "2022"), col=c("green","yellow","red","black"), lty = c(1,1), lwd = c(1,1), bty="n", cex=1)
```


Column
--------------------------------------------------------------
### **Canal endémico Dengue**

```{r, fig.width=8}
plot(canalend$semana, canalend$exito, type='l', ylim=c(0,50), xlim=c(1,52), col="green",lwd=2, xlab="Semana epidemiológica", ylab="Casos", cex=0.6, main = "")
lines(canalend$alerta, col="red",lwd=2, cex=0.7)
lines(canalend$media, col="yellow",lwd=2, cex=0.7)
lines(actual['210',], col="black",lwd=2, cex=0.7)
legend(10,50, c("IC inf 95%","Media", "IC sup 95%", "2022"), col=c("green","yellow","red","black"), lty = c(1,1), lwd = c(1,1), bty="n", cex=0.7)
```
